export type Document = {
  id: string;
  caseId: string;
  filename: string;
  category: string;
  type: string;
  uploadedAt: string;
  processingStatus: string;
  verificationStatus: string;
  sizeLabel: string;
  excerpt: string | null;
};

export const demoDocuments: Document[] = [
  {
    id: "doc-001",
    caseId: "case-2026-145",
    filename: "Dava_Dilekcesi_2026_145.pdf",
    category: "Dava Dilekçesi",
    type: "PDF",
    uploadedAt: "25 Şubat 2026",
    processingStatus: "HAZIR",
    verificationStatus: "DEMO — KURGUSAL DAVA VERİSİ",
    sizeLabel: "1.2 MB",
    excerpt: "DEMO — KURGUSAL DAVA VERİSİ. Davacı Deniz Aras, davalı Marmara Lojistik A.Ş.'ye karşı fazla çalışma, yıllık izin ve ücret alacağının tahsili için iş bu davayı açmıştır.",
  },
  {
    id: "doc-002",
    caseId: "case-2026-145",
    filename: "Cevap_Dilekcesi_2026_145.pdf",
    category: "Cevap Dilekçesi",
    type: "PDF",
    uploadedAt: "15 Mart 2026",
    processingStatus: "HAZIR",
    verificationStatus: "DEMO — KURGUSAL DAVA VERİSİ",
    sizeLabel: "0.9 MB",
    excerpt: "DEMO — KURGUSAL DAVA VERİSİ. Davalı, bordroların imzalı olduğunu, fazla çalışma iddiasının asılsız olduğunu ve yıllık izinlerin kullandırıldığını savunmaktadır.",
  },
  {
    id: "doc-003",
    caseId: "case-2026-145",
    filename: "Is_Sozlesmesi_Deniz_Aras.pdf",
    category: "Sözleşme",
    type: "PDF",
    uploadedAt: "12 Ocak 2025",
    processingStatus: "HAZIR",
    verificationStatus: "DEMO — KURGUSAL DAVA VERİSİ",
    sizeLabel: "0.4 MB",
    excerpt: "DEMO — KURGUSAL DAVA VERİSİ. 12.01.2025 tarihli iş sözleşmesi. Deniz Aras, Marmara Lojistik A.Ş.'de Lojistik Operatör pozisyonunda işe başlamıştır. Aylık brüt ücret: 28.000 TL.",
  },
  {
    id: "doc-004",
    caseId: "case-2026-145",
    filename: "Ucret_Bordrosu_2025_I-Yariyil.pdf",
    category: "Ücret Bordrosu",
    type: "PDF",
    uploadedAt: "30 Haziran 2025",
    processingStatus: "HAZIR",
    verificationStatus: "DEMO — KURGUSAL DAVA VERİSİ",
    sizeLabel: "2.1 MB",
    excerpt: "DEMO — KURGUSAL DAVA VERİSİ. 2025 yılının ilk yarısına ait aylık bordro kayıtları. Bordroya göre normal çalışma saatleri 09:00-18:00 olarak gösterilmiş, fazla çalışma ücreti yansıtılmamıştır.",
  },
  {
    id: "doc-005",
    caseId: "case-2026-145",
    filename: "Puantaj_Cizelgesi_2025.pdf",
    category: "Puantaj",
    type: "PDF",
    uploadedAt: "30 Aralık 2025",
    processingStatus: "INCELENIYOR",
    verificationStatus: "DEMO — KURGUSAL DAVA VERİSİ",
    sizeLabel: "1.8 MB",
    excerpt: "DEMO — KURGUSAL DAVA VERİSİ. Aylık puantaj kayıtları. Bazı aylarda 20:00'den sonra çıkış saatleri mevcuttur ancak fazla çalışma olarak işaretlenmemiştir. Eksik giriş-çıkış kayıtları mevcuttur.",
  },
  {
    id: "doc-006",
    caseId: "case-2026-145",
    filename: "WhatsApp_Yazismasi_Dökümü.pdf",
    category: "İletişim Kaydı",
    type: "PDF",
    uploadedAt: "10 Mart 2026",
    processingStatus: "HAZIR",
    verificationStatus: "DOĞRULANAMADI",
    sizeLabel: "3.5 MB",
    excerpt: "DEMO — KURGUSAL DAVA VERİSİ. Davacı ile iş yeri yöneticisi arasındaki WhatsApp yazışmaları. Mesai sonrası çalışma talimatları ve Gece 23:00'te gönderilen mesajlar mevcuttur. Kaynak: WHATSAPP MESAİ DIŞI ÇALIŞMA TALİMATLARI.",
  },
  {
    id: "doc-007",
    caseId: "case-2026-145",
    filename: "Yillik_Izin_Formu_2025.pdf",
    category: "İzin Formu",
    type: "PDF",
    uploadedAt: "18 Aralık 2025",
    processingStatus: "HAZIR",
    verificationStatus: "DEMO — KURGUSAL DAVA VERİSİ",
    sizeLabel: "0.3 MB",
    excerpt: "DEMO — KURGUSAL DAVA VERİSİ. Davacının 2025 yılına ait yıllık izin kullandırma formu. 14 gün izin kullandığı gösterilmiş ancak imza sahte olabilir. İmza doğrulaması gereklidir.",
  },
  {
    id: "doc-008",
    caseId: "case-2026-145",
    filename: "Ihtarname_12_01_2026.pdf",
    category: "İhtarname",
    type: "PDF",
    uploadedAt: "12 Ocak 2026",
    processingStatus: "HAZIR",
    verificationStatus: "DEMO — KURGUSAL DAVA VERİSİ",
    sizeLabel: "0.5 MB",
    excerpt: "DEMO — KURGUSAL DAVA VERİSİ. Davacı avukatı tarafından 12.01.2026 tarihinde gönderilen ihtarname. Fazla çalışma ve izin ücreti alacağının ödenmesi talep edilmiştir.",
  },
  {
    id: "doc-009",
    caseId: "case-2026-145",
    filename: "Durusma_Tutancagi_14_09_2026.pdf",
    category: "Duruşma Tutanağı",
    type: "PDF",
    uploadedAt: "14 Eylül 2026",
    processingStatus: "HAZIR",
    verificationStatus: "DEMO — KURGUSAL DAVA VERİSİ",
    sizeLabel: "0.6 MB",
    excerpt: "DEMO — KURGUSAL DAVA VERİSİ. 14.09.2026 tarihli duruşma tutanağı. Bilirkişi raporu sunuldu, taraflar beyanda bulundu. Bir sonraki duruşma: 20.01.2027.",
  },
  {
    id: "doc-010",
    caseId: "case-2026-145",
    filename: "Bilirkişi_Raporu_2026_145.pdf",
    category: "Bilirkişi Raporu",
    type: "PDF",
    uploadedAt: "20 Haziran 2026",
    processingStatus: "HAZIR",
    verificationStatus: "DEMO — KURGUSAL DAVA VERİSİ",
    sizeLabel: "4.2 MB",
    excerpt: "DEMO — KURGUSAL DAVA VERİSİ. Bilirkişi raporu: Fazla çalışma iddiası için yeterli delil bulunamamıştır. Yıllık izin kayıtları çelişkilidir. Ücret bordrosu ile banka hesap özeti arasında uyumsuzluk tespit edilmiştir.",
  },
];
